[build]
# target = "x86_64-unknown-linux-gnu"
# target = "aarch64-apple-darwin"
rustflags = [
  # https://nnethercote.github.io/perf-book/profiling.html#symbol-demangling
  "-Csymbol-mangling-version=v0",
  # "-Cdebuginfo=0",
  "-Ctarget-cpu=native",
  "-Zthreads=8",
]

[x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang-22"
rustflags = [
  "-Clink-arg=-fuse-ld=mold",
  # "-Zcodegen-backend=cranelift",
]

[target.aarch64-apple-darwin]
linker = "/usr/bin/clang"

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"
